def GIT_REPO_URL = "git@github.com:BridgePhase/hello-world.git";
def GIT_BRANCH = "CI-DEV";

node {
    printInfo("START BUILD")

    stage ("Clone Source Repository") {
        gitClone(GIT_REPO_URL, GIT_BRANCH)
    }

    stage ("Test") {

    }

    stage ("Merge") {

    }

    stage ("Deploy") {

    }

    printInfo("START BUILD")
}

def printInfo(text) {
    println "[ INFO ] --> " + text
}

def gitClone(git_repo_url, git_branch) {
    checkout changelog: false, poll: false, scm: [
            $class: 'GitSCM',
            branches: [[name: git_branch]],
            doGenerateSubmoduleConfigurations: false,
            extensions: [[$class: 'WipeWorkspace']],
            submoduleCfg: [],
            userRemoteConfigs: [[
                    credentialsId: 'jenkins-user-ssh',
                    url: git_repo_url
            ]]
    ]
}