def GIT_BASE_BRANCH = "master"
def SERVICE_VERSION = "1.0." + env.BUILD_NUMBER

node {
    printInfo("START BUILD")

    currentBuild.displayName = env.GIT_BRANCH + "-"+ env.BUILD_NUMBER

    stage ("Test") {
        printInfo("UNIT TEST")
        try {
            gradleWrapper("test", "--continue --stacktrace")
        } finally {
            archive "build/reports/**"
            junit '**/build/test-results/test/*.xml'
        }
        printInfo("INT TEST")
        try {
            gradleWrapper("intTest", "--stacktrace")
        } finally {
            archive "build/reports/intTest/**"
            junit '**/build/test-results/intTest/*.xml'
        }
        jacoco classPattern: '**/build/classes', exclusionPattern: '**/build/out/**'
    }
    /*
    stage ("Build Image") {
        gradleWrapper("assemble", "--stacktrace")
        def pullSpec = "622865517111.dkr.ecr.us-east-1.amazonaws.com/bridgephase-demo/helloworld:${SERVICE_VERSION}"
        sh returnStdout: false, script: """
        docker build -t ${pullSpec} -f docker/Dockerfile . 
        docker push ${pullSpec}
        """
    }
    */

    stage ("Merge") {

    }

    stage ("Deploy") {

    }

    printInfo("START BUILD")
}

def printInfo(text) {
    println "[ INFO ] --> " + text
}

def mergeTo(git_branch, git_base_branch, git_repo_url){
    checkout changelog: false, poll: false, scm: [
            $class: 'GitSCM',
            branches: [[name: git_branch]],
            doGenerateSubmoduleConfigurations: false,
            extensions: [[
                                 $class: 'PreBuildMerge',
                                 options: [fastForwardMode: 'FF', mergeRemote: 'origin', mergeStrategy: 'default', mergeTarget: git_base_branch]
                         ]],
            submoduleCfg: [],
            userRemoteConfigs: [[credentialsId: 'jenkins-user-ssh', url: git_repo_url]]
    ]
    println "Locally merged $git_branch to $git_base_branch"
}

def gradleWrapper(gradle_command, gradle_string){
    withEnv(['GRADLE_STRING=' + gradle_string,
             'GRADLE_COMMAND=' + gradle_command]){
        sh returnStdout: true, script: '''
            echo ${GRADLE_COMMAND}
            echo ${GRADLE_STRING}
            chmod +x gradlew
            ./gradlew ${GRADLE_COMMAND} ${GRADLE_STRING}
        '''
    }
}
